import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useWeb3React } from "@web3-react/core";
import { InjectedConnector } from "@web3-react/injected-connector";
import Upload from "../components/Upload";

export default function Home() {
  const injected = new InjectedConnector();
  const { activate, active, library: provider } = useWeb3React();

  async function connect() {
    try {
      await activate(injected);
    } catch (e) {
      console.log(e);
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>DeFeit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {active ? (
        <>
          <Upload active={active} provider={provider} />
        </>
      ) : (
        <>
          <div className={styles.main}>
            <h1 className={styles.title}>
              Welcome to{" "}
              <a
                href="https://www.globalgradshow.com/project/defeit/"
                target="_blank"
              >
                DeFeit!
              </a>
            </h1>
            <h3>Manufacturer Login:</h3>
            <button
              style={{
                background: "blue",
                color: "white",
                padding: "10px",
                borderRadius: "7px",
              }}
              onClick={() => connect()}
            >
              Connect Wallet
            </button>
          </div>
        </>
      )}
    </div>
  );
}
